@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}

### Criar aplicação
# @name criarAplicacao
POST {{host}}/aplicacoes
Content-Type: application/json

{
  "talhao": {
    "id": "550e8400-e29b-41d4-a716-446655440000"
  },
  "equipamento": {
    "id": "550e8400-e29b-41d4-a716-446655440001"
  },
  "tipoAplicacao": {
    "id": "550e8400-e29b-41d4-a716-446655440002"
  },
  "dataInicio": "2025-04-15T08:30:00",
  "dosagem": 2.5,
  "operador": "João Silva",
  "condicaoClimatica": "Ensolarado, vento leve",
  "observacoes": "Aplicação realizada conforme recomendação técnica"
}

### Guardar o ID da aplicação criado
@aplicacaoId = {{criarAplicacao.response.body.id}}

### Listar todas as aplicações (paginado)
GET {{host}}/aplicacoes?page=0&size=10
Content-Type: application/json

### Obter aplicação por ID
GET {{host}}/aplicacoes/{{aplicacaoId}}
Content-Type: application/json

### Atualizar aplicação
PUT {{host}}/aplicacoes/{{aplicacaoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "talhao": {
    "id": "550e8400-e29b-41d4-a716-446655440000"
  },
  "equipamento": {
    "id": "550e8400-e29b-41d4-a716-446655440001"
  },
  "tipoAplicacao": {
    "id": "550e8400-e29b-41d4-a716-446655440002"
  },
  "dataInicio": "2025-04-15T08:30:00",
  "dosagem": 3.0,
  "volumeAplicado": 150.0,
  "operador": "João Silva",
  "condicaoClimatica": "Ensolarado, vento moderado",
  "observacoes": "Ajuste na dosagem devido à infestação mais alta que o previsto"
}

### Excluir aplicação
DELETE {{host}}/aplicacoes/{{aplicacaoId}}
Authorization: Bearer {{token}}

### Buscar aplicações por talhão
GET {{host}}/aplicacoes/talhao/550e8400-e29b-41d4-a716-446655440000?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar aplicações por equipamento
GET {{host}}/aplicacoes/equipamento/550e8400-e29b-41d4-a716-446655440001?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar aplicações por tipo de aplicação
GET {{host}}/aplicacoes/tipo-aplicacao/550e8400-e29b-41d4-a716-446655440002?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar aplicações por status (finalizadas)
GET {{host}}/aplicacoes/finalizada/true?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Finalizar uma aplicação
PATCH  {{host}}/aplicacoes/{{aplicacaoId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "finalizada": true
}

### Finalizar uma aplicação
PATCH  {{host}}/aplicacoes/{{aplicacaoId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "finalizada": false
}
