@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}

### Login to obtain JWT token
# @name login
POST {{host}}/auth/login
Content-Type: application/json

{
  "username": "pedrosawczuk@proton.me",
  "password": "qVbuHNDk3a*z$!pkCr&h"
}

### Save token from the response
@authToken = {{login.response.body.token}}
@refreshToken = {{login.response.body.refreshToken}}
@idToken = {{login.response.body.idToken}}

### Validate token
POST {{host}}/auth/validate
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Refresh token
POST {{host}}/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}",
  "username": "pedrosawczuk@proton.me",
  "idToken": "{{idToken}}"
}

### Test a protected endpoint
GET {{host}}/api/aplicacoes
Content-Type: application/json
Authorization: Bearer {{authToken}}
