@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}

### Login
POST {{host}}/login
Content-Type: application/json

{
  "email": "admin@pulverizacao.com",
  "senha": "senha123"
}

### Teste de endpoint protegido (com JWT)
GET {{host}}/aplicacoes
Content-Type: application/json
Authorization: Bearer {{token}}
