@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}
@ID = 

### Listar todos os equipamentos (paginado)
GET {{host}}/equipamentos?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Obter equipamento por ID
GET {{host}}/equipamentos/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Criar equipamento
POST {{host}}/equipamentos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pulverizador Autopropelido",
  "modelo": "Uniport 3030",
  "fabricante": "Jacto",
  "anoFabricacao": 2023,
  "larguraBarra": 30.0,
  "capacidadeTanque": 3000.0,
  "numeroSerie": "JAC2023001"
}

### Atualizar equipamento
PUT {{host}}/equipamentos/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pulverizador Autopropelido Atualizado",
  "modelo": "Uniport 3030",
  "fabricante": "Jacto",
  "anoFabricacao": 2023,
  "larguraBarra": 32.0,
  "capacidadeTanque": 3000.0,
  "numeroSerie": "JAC2023001"
}

### Excluir equipamento
DELETE {{host}}/equipamentos/{{ID}}
Authorization: Bearer {{token}}

### Buscar equipamentos por nome
GET {{host}}/equipamentos/nome/pulverizador?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar equipamentos por fabricante
GET {{host}}/equipamentos/fabricante/Jacto?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar equipamentos por modelo
GET {{host}}/equipamentos/modelo/Uniport%203030?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}
