@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}
@ID = af91011f-9246-45e6-bbff-2cdc29430623

### Listar todos os talhões (paginado) BUG
GET {{host}}/talhoes?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Obter talhão por ID BUG
GET {{host}}/talhoes/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Criar talhão
POST {{host}}/talhoes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Talhão Norte",
  "areaHectares": 25.75,
  "cultura": "Soja",
  "variedade": "Intacta RR2 PRO",
  "coordenadasGeograficas": "-25.2456,-51.3658"
}

### Atualizar talhão BUG
PUT {{host}}/talhoes/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Talhão Norte Atualizado",
  "areaHectares": 27.5,
  "cultura": "Milho",
  "variedade": "BT PRO 3",
  "coordenadasGeograficas": "-25.2456,-51.3658"
}

### Excluir talhão
DELETE {{host}}/talhoes/{{ID}}
Authorization: Bearer {{token}}

### Buscar talhões por nome BUG
GET {{host}}/talhoes/nome/norte?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar talhões por cultura
GET {{host}}/talhoes/cultura/Soja?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}
