@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}

### Criar talhão
# @name criarTalhao
POST {{host}}/talhoes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Talhão Norte",
  "areaHectares": 25.75,
  "cultura": "Soja",
  "variedade": "Intacta RR2 PRO",
  "coordenadasGeograficas": "-25.2456,-51.3658"
}

### Guardar o ID do talhão criado
@talhaoId = {{criarTalhao.response.body.id}}

### Listar todos os talhões (paginado)
GET {{host}}/talhoes?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Obter talhão por ID
GET {{host}}/talhoes/{{talhaoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Atualizar talhão
PUT {{host}}/talhoes/{{talhaoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Talhão Norte Atualizado",
  "areaHectares": 27.5,
  "cultura": "Milho",
  "variedade": "BT PRO 3",
  "coordenadasGeograficas": "-25.2456,-51.3658"
}

### Excluir talhão
DELETE {{host}}/talhoes/{{talhaoId}}
Authorization: Bearer {{token}}

### Buscar talhões por nome
GET {{host}}/talhoes/nome/norte?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar talhões por cultura
GET {{host}}/talhoes/cultura/Soja?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}
