@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}
@ID = 83c1d2d8-6e81-49e5-9c9b-94d3d884f6ce

### Listar todos os tipos de aplicação (paginado) BUG
GET {{host}}/tipos-aplicacao?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Obter tipo de aplicação por ID BUG
GET {{host}}/tipos-aplicacao/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Criar tipo de aplicação
POST {{host}}/tipos-aplicacao
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Herbicida Pós-Emergente",
  "descricao": "Aplicação de herbicida após a emergência da cultura",
  "vazaoPadrao": 150.0,
  "tipoProduto": "Herbicida",
  "unidadeMedida": "L/ha"
}

### Atualizar tipo de aplicação BUG
PUT {{host}}/tipos-aplicacao/{{ID}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Herbicida Pós-Emergente Atualizado",
  "descricao": "Aplicação de herbicida após a emergência da cultura",
  "vazaoPadrao": 180.0,
  "tipoProduto": "Herbicida",
  "unidadeMedida": "L/ha"
}

### Excluir tipo de aplicação
DELETE {{host}}/tipos-aplicacao/{{ID}}
Authorization: Bearer {{token}}

### Buscar tipos de aplicação por nome BUG
GET {{host}}/tipos-aplicacao/nome/herbicida?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar tipos de aplicação por tipo de produto BUG
GET {{host}}/tipos-aplicacao/tipo-produto/Herbicida?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}
