@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}

### Criar equipamento
# @name criarEquipamento
POST {{host}}/api/equipamentos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pulverizador Autopropelido",
  "modelo": "Uniport 3030",
  "fabricante": "Jacto",
  "anoFabricacao": 2023,
  "larguraBarra": 30.0,
  "capacidadeTanque": 3000.0,
  "numeroSerie": "JAC2023001"
}

### Guardar o ID do equipamento criado
@equipamentoId = {{criarEquipamento.response.body.id}}

### Listar todos os equipamentos (paginado)
GET {{host}}/api/equipamentos?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Obter equipamento por ID
GET {{host}}/api/equipamentos/{{equipamentoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Atualizar equipamento
PUT {{host}}/api/equipamentos/{{equipamentoId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pulverizador Autopropelido Atualizado",
  "modelo": "Uniport 3030",
  "fabricante": "Jacto",
  "anoFabricacao": 2023,
  "larguraBarra": 32.0,
  "capacidadeTanque": 3000.0,
  "numeroSerie": "JAC2023001"
}

### Excluir equipamento
DELETE {{host}}/api/equipamentos/{{equipamentoId}}
Authorization: Bearer {{token}}

### Buscar equipamentos por nome
GET {{host}}/api/equipamentos/nome/pulverizador?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar equipamentos por fabricante
GET {{host}}/api/equipamentos/fabricante/Jacto?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Buscar equipamentos por modelo
GET {{host}}/api/equipamentos/modelo/Uniport%203030?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}
