@localUrl = {{$dotenv localUrl}}
@host = {{localUrl}}
@token = {{$dotenv token}}

### Criar usuário
# @name criarAdmin
POST {{host}}/api/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Admin Sistema",
  "email": "admin@pulverizacao.com",
  "senha": "senha123",
  "role": "ADMIN"
}

### Guardar o ID do Admin criado
@adminId = {{criarAdmin.response.body.id}}

### Obter usuário por ID
GET {{host}}/api/usuarios/{{adminId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Criar usuário técnico
# @name criarTecnico
POST {{host}}/api/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Carlos Técnico",
  "email": "carlos@pulverizacao.com",
  "senha": "senha123",
  "role": "TECNICO"
}

### Guardar o ID do Tecnico criado
@tecnicoId = {{criarTecnico.response.body.id}}

### Criar usuário operador
POST {{host}}/api/usuarios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Pedro Operador",
  "email": "pedro@pulverizacao.com",
  "senha": "senha123",
  "role": "OPERADOR"
}

### Atualizar usuário
PUT {{host}}/api/usuarios/{{adminId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Admin Sistema Atualizado",
  "email": "admin@pulverizacao.com",
  "senha": "senha123",
  "role": "ADMIN"
}

### Listar todos os usuários (paginado)
GET {{host}}/api/usuarios?page=0&size=10
Content-Type: application/json
Authorization: Bearer {{token}}

### Excluir usuário
DELETE {{host}}/api/usuarios/{{adminId}}
Authorization: Bearer {{token}}

### Desativar usuário
PATCH {{host}}/api/usuarios/{{tecnicoId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ativo": false
}

### Ativar usuário
PATCH {{host}}/api/usuarios/{{tecnicoId}}/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ativo": true
}
